# Generated by Django 2.0.6 on 2018-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('PointGuardFirstName', models.CharField(max_length=30)),
                ('PointGuardLastName', models.CharField(max_length=30)),
                ('PointGuardHeight', models.CharField(max_length=5)),
                ('PointGuardWeight', models.CharField(max_length=3)),
                ('PointGuardOffense', models.IntegerField()),
                ('PointGuardPassing', models.IntegerField()),
                ('PointGuardDefense', models.IntegerField()),
                ('ShootingGuardFirstName', models.CharField(max_length=30)),
                ('ShootingGuardLastName', models.CharField(max_length=30)),
                ('ShootingGuardHeight', models.CharField(max_length=5)),
                ('ShootingGuardWeight', models.CharField(max_length=3)),
                ('ShootingGuardOffense', models.IntegerField()),
                ('ShootingGuardPassing', models.IntegerField()),
                ('ShootingGuardDefense', models.IntegerField()),
                ('SmallForwardFirstName', models.CharField(max_length=30)),
                ('SmallForwardLastName', models.CharField(max_length=30)),
                ('SmallForwardHeight', models.CharField(max_length=5)),
                ('SmallForwardWeight', models.CharField(max_length=3)),
                ('SmallForwardOffense', models.IntegerField()),
                ('SmallForwardPassing', models.IntegerField()),
                ('SmallForwardDefense', models.IntegerField()),
                ('PowerForwardFirstName', models.CharField(max_length=30)),
                ('PowerForwardLastName', models.CharField(max_length=30)),
                ('PowerForwardHeight', models.CharField(max_length=5)),
                ('PowerForwardWeight', models.CharField(max_length=3)),
                ('PowerForwardOffense', models.IntegerField()),
                ('PowerForwardPassing', models.IntegerField()),
                ('PowerForwardDefense', models.IntegerField()),
                ('CenterFirstName', models.CharField(max_length=30)),
                ('CenterLastName', models.CharField(max_length=30)),
                ('CenterHeight', models.CharField(max_length=5)),
                ('CenterWeight', models.CharField(max_length=3)),
                ('CenterOffense', models.IntegerField()),
                ('CenterPassing', models.IntegerField()),
                ('CenterDefense', models.IntegerField()),
            ],
        ),
    ]
