# Generated by Django 2.0.6 on 2018-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180713_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='OpposingTeam',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
