# Generated by Django 2.0.6 on 2018-07-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_team_opposingteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Height', models.CharField(max_length=5)),
                ('Weight', models.CharField(max_length=3)),
                ('Scoring', models.IntegerField()),
                ('Passing', models.IntegerField()),
                ('Defense', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterDefense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterFirstName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterHeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterLastName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterPassing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterScoring',
        ),
        migrations.RemoveField(
            model_name='team',
            name='CenterWeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardDefense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardFirstName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardHeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardLastName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardPassing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardScoring',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PointGuardWeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardDefense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardFirstName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardHeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardLastName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardPassing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardScoring',
        ),
        migrations.RemoveField(
            model_name='team',
            name='PowerForwardWeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardDefense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardFirstName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardHeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardLastName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardPassing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardScoring',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ShootingGuardWeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardDefense',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardFirstName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardHeight',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardLastName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardPassing',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardScoring',
        ),
        migrations.RemoveField(
            model_name='team',
            name='SmallForwardWeight',
        ),
        migrations.AddField(
            model_name='team',
            name='Center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='PointGuard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pointguard', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='PowerForward',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='powerforward', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='ShootingGuard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shootingguard', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='SmallForward',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='smallforward', to='game.Player'),
            preserve_default=False,
        ),
    ]
