# Generated by Django 2.0.6 on 2018-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180718_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='CatchAndShoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='DenyPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='DenyShot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='HelpDefender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='PassFirst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='ShootFirst',
            field=models.BooleanField(default=False),
        ),
    ]
