# Generated by Django 2.0.6 on 2018-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180722_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='User',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
