# Generated by Django 2.0.6 on 2018-07-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='ip',
        ),
    ]
