# Generated by Django 2.0.6 on 2018-08-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_team_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record', models.CharField(max_length=5)),
                ('WeekOneResult', models.CharField(max_length=9)),
                ('WeekTwoResult', models.CharField(max_length=9)),
                ('WeekThreeResult', models.CharField(max_length=9)),
                ('WeekFourResult', models.CharField(max_length=9)),
                ('WeekFiveResult', models.CharField(max_length=9)),
                ('WeekSixResult', models.CharField(max_length=9)),
                ('WeekSevenResult', models.CharField(max_length=9)),
                ('WeekEightResult', models.CharField(max_length=9)),
                ('WeekNineResult', models.CharField(max_length=9)),
                ('UserTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userteam', to='game.Team')),
                ('WeekEightOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekEight', to='game.Team')),
                ('WeekFiveOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekFive', to='game.Team')),
                ('WeekFourOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekFour', to='game.Team')),
                ('WeekNineOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekNine', to='game.Team')),
                ('WeekOneOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekOne', to='game.Team')),
                ('WeekSevenOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekSeven', to='game.Team')),
                ('WeekSixOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekSix', to='game.Team')),
                ('WeekThreeOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekThree', to='game.Team')),
                ('WeekTwoOpponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WeekTwo', to='game.Team')),
            ],
        ),
    ]
