# Generated by Django 2.0.6 on 2018-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='FreeAgent',
            field=models.BooleanField(default=False),
        ),
    ]
