# Generated by Django 2.0.6 on 2018-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_freeagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='CurrentWeek',
            field=models.IntegerField(default=1),
        ),
    ]
